---
title: Jekyll boilerplate
timezone: America/New_York
permalink: pretty
exclude:
- Gruntfile.js
- webpack.config.js
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
- assets/scripts/src
gems:
- jekyll-seo-tag
- jekyll-sitemap
sass:
  sass_dir: assets/styles/
  style: compressed
